"""add campaign and gallery tables

Revision ID: fc7f83892ef1
Revises: 20260206_170600
Create Date: 2026-02-06 17:33:43.817252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7f83892ef1'
down_revision: Union[str, Sequence[str], None] = '20260206_170600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('schedule_interval_hours', sa.Integer(), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('comparison_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('comparison_type', sa.String(length=30), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_snapshots_id'), 'comparison_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_comparison_snapshots_workspace_id'), 'comparison_snapshots', ['workspace_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operation_logs_workspace_id'), 'operation_logs', ['workspace_id'], unique=False)
    op.create_table('intent_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_clusters_campaign_id'), 'intent_clusters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_intent_clusters_id'), 'intent_clusters', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('output_schema_version', sa.String(length=50), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_campaign_id'), 'prompt_templates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_table('campaign_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_target_brand', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'company_profile_id', name='uq_campaign_company')
    )
    op.create_index(op.f('ix_campaign_companies_campaign_id'), 'campaign_companies', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_companies_company_profile_id'), 'campaign_companies', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_campaign_companies_id'), 'campaign_companies', ['id'], unique=False)
    op.create_table('campaign_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('llm_providers', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('completed_queries', sa.Integer(), nullable=False),
    sa.Column('failed_queries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_runs_campaign_id'), 'campaign_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_runs_id'), 'campaign_runs', ['id'], unique=False)
    op.create_table('query_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('intent_cluster_id', sa.Integer(), nullable=True),
    sa.Column('query_type', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intent_cluster_id'], ['intent_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_definitions_campaign_id'), 'query_definitions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_query_definitions_id'), 'query_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_query_definitions_intent_cluster_id'), 'query_definitions', ['intent_cluster_id'], unique=False)
    op.create_table('query_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_definition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('persona_type', sa.String(length=20), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['query_definition_id'], ['query_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_versions_id'), 'query_versions', ['id'], unique=False)
    op.create_index(op.f('ix_query_versions_query_definition_id'), 'query_versions', ['query_definition_id'], unique=False)
    op.create_table('run_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_run_id', sa.Integer(), nullable=False),
    sa.Column('query_version_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_model_version', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_run_id'], ['campaign_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_version_id'], ['query_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_responses_campaign_run_id'), 'run_responses', ['campaign_run_id'], unique=False)
    op.create_index(op.f('ix_run_responses_id'), 'run_responses', ['id'], unique=False)
    op.create_index(op.f('ix_run_responses_query_version_id'), 'run_responses', ['query_version_id'], unique=False)
    op.create_table('response_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('run_response_id', sa.Integer(), nullable=False),
    sa.Column('label_type', sa.String(length=20), nullable=False),
    sa.Column('label_key', sa.String(length=100), nullable=False),
    sa.Column('label_value', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_response_id'], ['run_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_labels_id'), 'response_labels', ['id'], unique=False)
    op.create_index(op.f('ix_response_labels_run_response_id'), 'response_labels', ['run_response_id'], unique=False)
    op.create_index(op.f('ix_response_labels_workspace_id'), 'response_labels', ['workspace_id'], unique=False)
    op.create_table('run_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_response_id', sa.Integer(), nullable=False),
    sa.Column('cited_brand', sa.String(length=255), nullable=False),
    sa.Column('citation_url', sa.String(length=500), nullable=True),
    sa.Column('citation_domain', sa.String(length=255), nullable=True),
    sa.Column('citation_span', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('position_in_response', sa.Integer(), nullable=False),
    sa.Column('is_target_brand', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_response_id'], ['run_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_citations_id'), 'run_citations', ['id'], unique=False)
    op.create_index(op.f('ix_run_citations_run_response_id'), 'run_citations', ['run_response_id'], unique=False)
    op.create_table('citation_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_citation_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_citation_id'], ['run_citations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_reviews_id'), 'citation_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_citation_reviews_run_citation_id'), 'citation_reviews', ['run_citation_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN TYPE - skipping enum conversions
    # Tables will use VARCHAR instead of Enum types (compatible with SQLite)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_llm_responses', type_='foreignkey')
    op.drop_constraint(None, 'raw_llm_responses', type_='foreignkey')
    op.create_foreign_key(None, 'raw_llm_responses', 'pipeline_jobs', ['pipeline_job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'raw_llm_responses', 'expanded_queries', ['query_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_raw_llm_responses_query_id'), 'raw_llm_responses', ['query_id'], unique=False)
    op.create_index(op.f('ix_raw_llm_responses_pipeline_job_id'), 'raw_llm_responses', ['pipeline_job_id'], unique=False)
    op.create_index(op.f('ix_raw_llm_responses_llm_provider'), 'raw_llm_responses', ['llm_provider'], unique=False)
    op.alter_column('raw_llm_responses', 'latency_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('raw_llm_responses', 'llm_provider',
               existing_type=sa.Enum('OPENAI', 'GEMINI', name='llmprovider'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'query_sets', type_='foreignkey')
    op.drop_constraint(None, 'query_sets', type_='foreignkey')
    op.create_foreign_key(None, 'query_sets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'query_sets', 'company_profiles', ['company_profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_query_sets_owner_id'), 'query_sets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_query_sets_company_profile_id'), 'query_sets', ['company_profile_id'], unique=False)
    op.drop_constraint(None, 'pipeline_jobs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_jobs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_jobs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_jobs', 'query_sets', ['query_set_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_jobs', 'company_profiles', ['company_profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pipeline_jobs_status'), 'pipeline_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_query_set_id'), 'pipeline_jobs', ['query_set_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_owner_id'), 'pipeline_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_company_profile_id'), 'pipeline_jobs', ['company_profile_id'], unique=False)
    op.alter_column('pipeline_jobs', 'status',
               existing_type=sa.Enum('PENDING', 'GENERATING_CATEGORIES', 'EXPANDING_QUERIES', 'EXECUTING_QUERIES', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'pipeline_categories', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_categories', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_categories', 'query_sets', ['query_set_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_categories', 'company_profiles', ['company_profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pipeline_categories_query_set_id'), 'pipeline_categories', ['query_set_id'], unique=False)
    op.create_index(op.f('ix_pipeline_categories_llm_provider'), 'pipeline_categories', ['llm_provider'], unique=False)
    op.create_index(op.f('ix_pipeline_categories_company_profile_id'), 'pipeline_categories', ['company_profile_id'], unique=False)
    op.alter_column('pipeline_categories', 'llm_provider',
               existing_type=sa.Enum('OPENAI', 'GEMINI', name='llmprovider'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'gemini'"))
    op.alter_column('pipeline_categories', 'persona_type',
               existing_type=sa.Enum('CONSUMER', 'INVESTOR', name='personatype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'expanded_queries', type_='foreignkey')
    op.create_foreign_key(None, 'expanded_queries', 'pipeline_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_expanded_queries_status'), 'expanded_queries', ['status'], unique=False)
    op.create_index(op.f('ix_expanded_queries_category_id'), 'expanded_queries', ['category_id'], unique=False)
    op.alter_column('expanded_queries', 'status',
               existing_type=sa.Enum('PENDING', 'EXECUTING', 'COMPLETED', 'FAILED', name='expandedquerystatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_citation_reviews_run_citation_id'), table_name='citation_reviews')
    op.drop_index(op.f('ix_citation_reviews_id'), table_name='citation_reviews')
    op.drop_table('citation_reviews')
    op.drop_index(op.f('ix_run_citations_run_response_id'), table_name='run_citations')
    op.drop_index(op.f('ix_run_citations_id'), table_name='run_citations')
    op.drop_table('run_citations')
    op.drop_index(op.f('ix_response_labels_workspace_id'), table_name='response_labels')
    op.drop_index(op.f('ix_response_labels_run_response_id'), table_name='response_labels')
    op.drop_index(op.f('ix_response_labels_id'), table_name='response_labels')
    op.drop_table('response_labels')
    op.drop_index(op.f('ix_run_responses_query_version_id'), table_name='run_responses')
    op.drop_index(op.f('ix_run_responses_id'), table_name='run_responses')
    op.drop_index(op.f('ix_run_responses_campaign_run_id'), table_name='run_responses')
    op.drop_table('run_responses')
    op.drop_index(op.f('ix_query_versions_query_definition_id'), table_name='query_versions')
    op.drop_index(op.f('ix_query_versions_id'), table_name='query_versions')
    op.drop_table('query_versions')
    op.drop_index(op.f('ix_query_definitions_intent_cluster_id'), table_name='query_definitions')
    op.drop_index(op.f('ix_query_definitions_id'), table_name='query_definitions')
    op.drop_index(op.f('ix_query_definitions_campaign_id'), table_name='query_definitions')
    op.drop_table('query_definitions')
    op.drop_index(op.f('ix_campaign_runs_id'), table_name='campaign_runs')
    op.drop_index(op.f('ix_campaign_runs_campaign_id'), table_name='campaign_runs')
    op.drop_table('campaign_runs')
    op.drop_index(op.f('ix_campaign_companies_id'), table_name='campaign_companies')
    op.drop_index(op.f('ix_campaign_companies_company_profile_id'), table_name='campaign_companies')
    op.drop_index(op.f('ix_campaign_companies_campaign_id'), table_name='campaign_companies')
    op.drop_table('campaign_companies')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_campaign_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_intent_clusters_id'), table_name='intent_clusters')
    op.drop_index(op.f('ix_intent_clusters_campaign_id'), table_name='intent_clusters')
    op.drop_table('intent_clusters')
    op.drop_index(op.f('ix_operation_logs_workspace_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_comparison_snapshots_workspace_id'), table_name='comparison_snapshots')
    op.drop_index(op.f('ix_comparison_snapshots_id'), table_name='comparison_snapshots')
    op.drop_table('comparison_snapshots')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
